### PR TITLE
Fix Node Require

### PR DESCRIPTION
**Pull request by devotox**
- This uses the common re-export pattern to allow you to use ES6 fully while still working for Node JS
- I have added a yarn.lock file - Helps people using yarn (me) install faster (hope thats ok)  
- Fixes https://github.com/anvk/google-stocks/issues/5

### CODE REVIEW

**Review by anvk — CHANGES_REQUESTED** [review]
Thanks a lot! And it looks great. Could you just please remove yarn.lock here. I'm aware that some developers are using yarn but I want to stick with default npm for this module to be more generic.

**Comment by devotox** [comment]
Done!

**Comment by anvk** [comment]
Thanks a lot for fixing this! Much appreciated.

**Comment by anvk** [comment]
Ah we forgot to bump the version. I did it myself and publish to NPM. version 2.0.1 is now available to public with your changes. Thanks again.

**Comment by devotox** [comment]
Thank you sire!

**Pull request merged**
